"""empty message

Revision ID: 133d26e5990e
Revises: 312add1b6289
Create Date: 2014-12-18 16:18:16.399962

"""

# revision identifiers, used by Alembic.
revision = '133d26e5990e'
down_revision = '312add1b6289'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commodity', sa.Column('numeric', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commodity', 'numeric')
    ### end Alembic commands ###
