"""empty message

Revision ID: 18e407ceb8be
Revises: e5d8b22056a
Create Date: 2014-12-06 17:05:59.042000

"""

# revision identifiers, used by Alembic.
revision = '18e407ceb8be'
down_revision = 'e5d8b22056a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=250), nullable=True),
    sa.Column('lname', sa.String(length=250), nullable=True),
    sa.Column('pname', sa.String(length=250), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('passport', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=250), nullable=True),
    sa.Column('lname', sa.String(length=250), nullable=True),
    sa.Column('pname', sa.String(length=250), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('passport', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('way_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=250), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('pointsale_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['pointsale_id'], ['point_sale.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['receiver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('way_bill')
    op.drop_table('receiver')
    op.drop_table('point_sale')
    op.drop_table('seller')
    ### end Alembic commands ###
