"""empty message

Revision ID: 1d526f51ad34
Revises: c80bd2e6402
Create Date: 2014-10-13 00:55:03.240088

"""

# revision identifiers, used by Alembic.
revision = '1d526f51ad34'
down_revision = 'c80bd2e6402'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('from_', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('is_handling', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mails')
    ### end Alembic commands ###
