"""empty message

Revision ID: 1ddd16fdc493
Revises: 4470e40d87b7
Create Date: 2014-12-09 15:52:37.234544

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '1ddd16fdc493'
down_revision = '4470e40d87b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_sale_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pointsale_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], ),
    sa.ForeignKeyConstraint(['pointsale_id'], ['point_sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'acceptance', sa.Column('pointsale_id', sa.Integer(), nullable=True))
    op.add_column(u'acceptance', sa.Column('waybill_id', sa.Integer(), nullable=True))

    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_column(u'good', 'count')
        except Exception as exc:
            pass
    else:
        op.drop_column(u'good', 'count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'good', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column(u'acceptance', 'waybill_id')
    op.drop_column(u'acceptance', 'pointsale_id')
    op.drop_table('point_sale_item')
    ### end Alembic commands ###
