"""empty message

Revision ID: 1ee73f6932eb
Revises: 587f7e488d1d
Create Date: 2014-10-22 14:28:19.007529

"""

# revision identifiers, used by Alembic.
revision = '1ee73f6932eb'
down_revision = '587f7e488d1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('date_from', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'date_from')
    ### end Alembic commands ###
