"""empty message

Revision ID: 2067dce9ed01
Revises: 1ddd16fdc493
Create Date: 2014-12-09 16:00:31.908981

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '2067dce9ed01'
down_revision = '1ddd16fdc493'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_column('good', 'is_confirm')
        except Exception as exc:
            pass
    else:
        op.drop_column('good', 'is_confirm')
    op.add_column('invoice_item', sa.Column('fact_count', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_item', 'fact_count')
    op.add_column('good', sa.Column('is_confirm', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
