"""empty message

Revision ID: 223a10a61da8
Revises: 180d24effd4a
Create Date: 2014-11-17 14:09:26.883518

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '223a10a61da8'
down_revision = '180d24effd4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('is_confirm', sa.BOOLEAN(), nullable=True))
    op.add_column('retail_invoice_item', sa.Column('good_id', sa.Integer(), nullable=True))
    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_column('retail_invoice_item', 'price_id')
            op.drop_column('retail_invoice_item', 'commodity_id')
            op.drop_column('retail_invoice_item', 'full_name')
        except Exception as exc:
            pass
    else:
        op.drop_column('retail_invoice_item', 'price_id')
        op.drop_column('retail_invoice_item', 'commodity_id')
        op.drop_column('retail_invoice_item', 'full_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retail_invoice_item', sa.Column('full_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('retail_invoice_item', sa.Column('commodity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('retail_invoice_item', sa.Column('price_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('retail_invoice_item', 'good_id')
    op.drop_column('good', 'is_confirm')
    ### end Alembic commands ###
