"""empty message

Revision ID: 31016f83e1b9
Revises: 1d526f51ad34
Create Date: 2014-10-14 09:51:25.866597

"""

# revision identifiers, used by Alembic.
revision = '31016f83e1b9'
down_revision = '1d526f51ad34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('mail_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'mail_id')
    ### end Alembic commands ###
