"""empty message

Revision ID: 312add1b6289
Revises: 4d18cb636564
Create Date: 2014-12-11 19:19:05.161137

"""

# revision identifiers, used by Alembic.
revision = '312add1b6289'
down_revision = '4d18cb636564'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('way_bill', sa.Column('pointsale_from_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('way_bill', 'pointsale_from_id')
    ### end Alembic commands ###
