"""empty message

Revision ID: 36c91eb7c263
Revises: 133d26e5990e
Create Date: 2014-12-19 15:29:09.538721

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '36c91eb7c263'
down_revision = '133d26e5990e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_parish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('number_local_from', sa.String(length=250), nullable=True),
    sa.Column('number_global_from', sa.String(length=250), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('NDS', sa.DECIMAL(), nullable=True),
    sa.Column('price_prev', sa.DECIMAL(), nullable=True),
    sa.Column('price_post', sa.DECIMAL(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_column(u'price', 'number_local')
            op.drop_column(u'price', 'date_from')
            op.drop_column(u'price', 'price_post')
            op.drop_column(u'price', 'price_prev')
            op.drop_column(u'price', 'commodity_id')
            op.drop_column(u'price', 'number_global')
            op.drop_column(u'price', 'NDS')
        except Exception as exc:
            pass
    else:
        op.drop_column(u'price', 'number_local')
        op.drop_column(u'price', 'date_from')
        op.drop_column(u'price', 'price_post')
        op.drop_column(u'price', 'price_prev')
        op.drop_column(u'price', 'commodity_id')
        op.drop_column(u'price', 'number_global')
        op.drop_column(u'price', 'NDS')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'price', sa.Column('NDS', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column(u'price', sa.Column('number_global', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column(u'price', sa.Column('commodity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'price', sa.Column('price_prev', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column(u'price', sa.Column('price_post', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column(u'price', sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column(u'price', sa.Column('number_local', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_table('price_parish')
    ### end Alembic commands ###
