"""empty message

Revision ID: 39f400c7fa17
Revises: 3cd33a83c1af
Create Date: 2014-10-20 19:23:31.602690

"""

# revision identifiers, used by Alembic.
revision = '39f400c7fa17'
down_revision = '3cd33a83c1af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailinvoice_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=250), nullable=True),
    sa.Column('commodity_id', sa.Integer(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.ForeignKeyConstraint(['retailinvoice_id'], ['retail_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retail_invoice_item')
    ### end Alembic commands ###
