"""empty message

Revision ID: 3cd33a83c1af
Revises: 4f8d0321cbca
Create Date: 2014-10-20 19:22:43.824167

"""

# revision identifiers, used by Alembic.
revision = '3cd33a83c1af'
down_revision = '4f8d0321cbca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=250), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retail_invoice')
    ### end Alembic commands ###
