"""empty message

Revision ID: 414a868e6848
Revises: None
Create Date: 2014-10-10 18:50:19.228374

"""

# revision identifiers, used by Alembic.
revision = '414a868e6848'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=250), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('sum_without_NDS', sa.DECIMAL(), nullable=True),
    sa.Column('sum_with_NDS', sa.DECIMAL(), nullable=True),
    sa.Column('sum_NDS', sa.DECIMAL(), nullable=True),
    sa.Column('weight', sa.DECIMAL(), nullable=True),
    sa.Column('responsible', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('remission', sa.DECIMAL(), nullable=True),
    sa.Column('NDS', sa.DECIMAL(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price_prev', sa.Float(), nullable=True),
    sa.Column('price_post', sa.Float(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('count_order', sa.Integer(), nullable=True),
    sa.Column('count_postorder', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price_without_NDS', sa.DECIMAL(), nullable=True),
    sa.Column('price_with_NDS', sa.DECIMAL(), nullable=True),
    sa.Column('sum_without_NDS', sa.DECIMAL(), nullable=True),
    sa.Column('sum_NDS', sa.DECIMAL(), nullable=True),
    sa.Column('rate_NDS', sa.DECIMAL(), nullable=True),
    sa.Column('sum_with_NDS', sa.DECIMAL(), nullable=True),
    sa.Column('thematic', sa.String(length=250), nullable=True),
    sa.Column('count_whole_pack', sa.Integer(), nullable=True),
    sa.Column('placer', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_item')
    op.drop_table('order_item')
    op.drop_table('order')
    op.drop_table('invoice')
    op.drop_table('provider')
    op.drop_table('commodity')
    ### end Alembic commands ###
