"""empty message

Revision ID: 4470e40d87b7
Revises: 18e407ceb8be
Create Date: 2014-12-07 17:21:08.993000

"""

# revision identifiers, used by Alembic.
revision = '4470e40d87b7'
down_revision = '18e407ceb8be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('way_bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waybill_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], ),
    sa.ForeignKeyConstraint(['waybill_id'], ['way_bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('way_bill_items')
    ### end Alembic commands ###
