"""empty message

Revision ID: 460fbb524369
Revises: 5a81db1e9df1
Create Date: 2014-12-29 17:09:05.021000

"""

# revision identifiers, used by Alembic.
revision = '460fbb524369'
down_revision = '5a81db1e9df1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
