"""empty message

Revision ID: 52363779f642
Revises: 14cf2440b756
Create Date: 2014-10-15 15:06:14.465265

"""

# revision identifiers, used by Alembic.
from sqlite3 import OperationalError
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '52363779f642'
down_revision = '14cf2440b756'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_column('invoice', 'mail_id')
        except Exception as exc:
            pass
    else:
        op.drop_column('invoice', 'mail_id')
    op.add_column('mails', sa.Column('invoice_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mails', 'invoice_id')
    op.add_column('invoice', sa.Column('mail_id', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
