"""empty message

Revision ID: 587f7e488d1d
Revises: 39f400c7fa17
Create Date: 2014-10-20 19:24:47.341320

"""

# revision identifiers, used by Alembic.
revision = '587f7e488d1d'
down_revision = '39f400c7fa17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retail_invoice', sa.Column('file', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retail_invoice', 'file')
    ### end Alembic commands ###
