"""empty message

Revision ID: 5a81db1e9df1
Revises: 36c91eb7c263
Create Date: 2014-12-19 20:33:31.630526

"""

# revision identifiers, used by Alembic.
revision = '5a81db1e9df1'
down_revision = '36c91eb7c263'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('number_global', sa.String(length=250), nullable=True))
    op.add_column('good', sa.Column('number_local', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('good', 'number_local')
    op.drop_column('good', 'number_global')
    ### end Alembic commands ###
