"""empty message

Revision ID: c80bd2e6402
Revises: 414a868e6848
Create Date: 2014-10-10 19:07:18.404703

"""

# revision identifiers, used by Alembic.
revision = 'c80bd2e6402'
down_revision = '414a868e6848'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_item', sa.Column('full_name', sa.String(length=250), nullable=True))
    op.add_column('invoice_item', sa.Column('number', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_item', 'number')
    op.drop_column('invoice_item', 'full_name')
    ### end Alembic commands ###
